enum TokenType {
  EndOf = "EndOf",
  String = "String",
  Int = "Int",
  Float = "Float",
  Bool = "Bool",
  Nil = "Nil",
  Keyword = "Keyword",
  Identifier = "Identifier",
  OperatorAdd = "OperatorAdd",
  OperatorSubtract = "OperatorSubtract",
  OperatorMultiply = "OperatorMultiply",
  OperatorDivide = "OperatorDivide",
  OperatorModulo = "OperatorModulo",
  OperatorAssign = "OperatorAssign",
  OperatorAssignMinus = "OperatorAssignMinus",
  OperatorAssignPlus = "OperatorAssignPlus",
  OperatorEqual = "OperatorEqual",
  OperatorNotEqual = "OperatorNotEqual",
  OperatorGreaterThan = "OperatorGreaterThan",
  OperatorLessThan = "OperatorLessThan",
  OperatorGreaterThanOrEqual = "OperatorGreaterThanOrEqual",
  OperatorLessThanOrEqual = "OperatorLessThanOrEqual",
  OperatorLogicalAnd = "LogicalAnd",
  OperatorAnd = "OperatorAnd",
  OperatorLogicalOr = "LogicalOr",
  OperatorOr = "OperatorOr",
  OperatorNot = "OperatorNot",
  BraceOpen = "BraceOpen",
  BraceClose = "BraceClose",
  BracketOpen = "BracketOpen",
  BracketClose = "BracketClose",
  ParenthesisOpen = "ParenthesisOpen",
  ParenthesisClose = "ParenthesisClose",
  Comma = "Comma",
  Period = "Period",
  QuoteDouble = "QuoteDouble",
  QuoteSingle = "QuoteSingle",
  Semicolon = "Semicolon",
  Colon = "Colon",
}

enum TokenList {
  BraceOpen = "{",
  BraceClose = "}",
  BracketOpen = "[",
  BracketClose = "]",
  ParenthesisOpen = "(",
  ParenthesisClose = ")",
  Comma = ",",
  Period = ".",
  QuoteDouble = '"',
  QuoteSingle = "'",
  Semicolon = ";",
  Colon = ":",
}

enum OperatorType {
  Add = "+",
  Subtract = "-",
  Multiply = "*",
  Divide = "/",
  Modulo = "%",
  Assign = "=",
  AssignMinus = "-=",
  AssignPlus = "+=",
  Equal = "==",
  NotEqual = "!=",
  GreaterThan = ">",
  LessThan = "<",
  GreaterThanOrEqual = ">=",
  LessThanOrEqual = "<=",
  LogicalAnd = "&",
  And = "&&",
  LogicalOr = "|",
  Or = "||",
  Not = "!",
}

enum KeywordType {
  Var = "var",
  Func = "func",
  Import = "import",
  Export = "export",
}

export { TokenList, TokenType, OperatorType, KeywordType };
